//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dinobazis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dinok
    {
        public int id { get; set; }
        public string nev { get; set; }
        public int felfedezo_id { get; set; }
        public int felfedezes_datuma { get; set; }
        public string mikorelt { get; set; }
        public string lelohelyek { get; set; }
        public string elohelyek { get; set; }
        public string taplalek { get; set; }
        public int taplalkozasi_forma_id { get; set; }
        public string testmeret { get; set; }
        public string testtomeg { get; set; }
        public string leiras { get; set; }
        public byte[] kep { get; set; }
    
        public virtual felfedezok felfedezok { get; set; }
        public virtual taplalkozasi_forma taplalkozasi_forma { get; set; }
    }
}
