//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dinobazis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taplalkozasi_forma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public taplalkozasi_forma()
        {
            this.dinok = new HashSet<dinok>();
        }
    
        public int id { get; set; }
        public string nev { get; set; }
        public string tud_elnevezes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dinok> dinok { get; set; }
    }
}
